[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "google-java-format", args = ["-"] }
auto-format = true
language-servers = ["jdtls"]

[language-server.kotlin-language-server]
command = "kotlin-lsp"
args = [
"--stdio",
"--system-path", "/home/fizlrock/bins/kotlin-lsp/cache"
]

[language-server.jdtls]
command = "jdtls"
args = [
]

[[language]]
name = "xml"
auto-format = true
formatter = { command = "xmllint", args = ["--format", "-"] }


[language-server.jedi]
command = "jedi-language-server"
[language-server.jedi.config]
workspace = { extraPaths = ["/home/fizlrock/code/home-assistant/valve-controller/.venv/typings"] }

[language-server.ty]
command = "ty"
args = [
    "--extra-paths",
    "/home/fizlrock/code/home-assistant/valve-controller/.venv/typings/"
]


##############################
## Configuration for lsp-ai ##
##############################

[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.model1]
type = "ollama"
model = "gemma3:4b"

[language-server.lsp-ai.config.completion]
model = "model1"

[language-server.lsp-ai.config.completion.parameters]
max_tokens = 32
max_context = 1024


#################################
## Configuration for languages ##
#################################
## Configure other languages here
